### ISSUE TITLE
瀑布流还是有广告

### ISSUE THREAD

**Issue by yujincheng08** [RealHeart/ThisReallyLite#1]
![Screenshot_2022-11-26-14-16-47-306_com weico international](https://user-images.githubusercontent.com/5022927/204075160-b26b9054-12ea-42a7-8d59-72853defbd41.jpg)

**Comment by MartinKayJr** [comment]
提的好，让真心找HOOK点。(滑稽

**Comment by RealHeart** [comment]
fixed in 69547e6
released in [v1.0.1](https://github.com/RealHeart/ThisReallyLite/releases/tag/v1.0.1)
